### ISSUE TITLE
feature request: 在搜索的时候，可否区分经，律，论的部分，很多时候只想搜“经”的部分。

### ISSUE THREAD

**Issue by yuqianyi1001** [Yuanuo/cbeta-explorer#13]
feature request: 在搜索的时候，可否区分经，律，论的部分，很多时候只想搜“经”的部分。

**Comment by Yuanuo** [comment]
经藏数据是由CBETA组织维护的，目前没有发现典籍数据中有任何经、律、论的标记，所以暂时是没办法实现这个功能的。

**Comment by yuqianyi1001** [comment]
> 经藏数据是由CBETA组织维护的，目前没有发现典籍数据中有任何经、律、论的标记，所以暂时是没办法实现这个功能的。

虽说如此，其实还是可以判断的，比如，根据“经”名。绝大多数佛经，都是以“经”结尾的。
“坛经” 是个例外了。

或者变通下，就是支持组合搜索。
如根据标题过滤。 可以过滤只有“经”字的部分。 或仅仅保留以“经”结尾的。

**Comment by yuqianyi1001** [comment]
**补充理由。**

因为很多时候，想要查找经文，而非“论述”。
原因在于，有些论述的观点，是没有经文对照的。
我看过不少论述的地方说，某某经有什么，结果就差不多。

在没有电脑的时代，要确保某部经，尤其是大经里面时候包含一句话，是很难很难的事情的。

但我们今天则完全不同，全文检索很方便，所以，才想要多查查经典原文，而非仅仅是论述。

以上。
谢谢。

**Comment by Yuanuo** [comment]
ok，我研究一下

**Comment by k79e** [comment]
这个功能网页版早都有了. 能限制搜索区间.

**Comment by Yuanuo** [comment]
目前还没有这方面的信息，仅从典籍标题上判断也不可行，因为标题没有规则。

虽然有很多 经 是以经字结尾的，但也有很多 论 是以经字结尾的，类似于 “御註圓覺經”；
有些标题上带经字的但实际是论，类似于“華嚴經三十九品大意”；
律的部分也是很多与经论重合的，所以只是根据标题来判断也不准确。

**Comment by yuqianyi1001** [comment]
对，肯定不准确，但可以解决80%
以上的问题了。从搜索的角度来说，一是根据文本过滤，二是根据标题过滤。可以包含什么和不包含什么。四个条件，可以满足90% 以上的搜索需求的。

坛经不是经，这是很容易想到的了。

**Comment by k79e** [comment]
增加一个对结果的排除选项, 可以对标题 或者对内容 , 或者标题和内容进行正则排除.
应该是具有很大帮助的.

**Comment by Yuanuo** [comment]
24.03.25 版增加了此过滤。

![image](https://github.com/Yuanuo/cbeta-explorer/assets/10892032/9ada709a-2ae4-41d3-ad6e-892e45374cec)

如果使用中发现有明显的分类错误也请反馈。
