### ISSUE TITLE
添加字典和自動査詢

### ISSUE THREAD

**Issue by Pantyhose-X** [Yuanuo/cbeta-explorer#14]
添加字典 [說文解字注](https://github.com/lagrange-landada/shuowen) 這是經過點校的版本。[點校人員](https://zhuanlan.zhihu.com/p/463271445)

添加 劃詞査詢字典 功能，此功能必須在設定裏選定字典

**Comment by Yuanuo** [comment]
可以的，下一次发布更新时会增加这两个。

**Comment by Yuanuo** [comment]
已加入 说文解字 词典；
已支持 划词查词 功能，默认Ctrl+鼠标左键选择文字后触发，在设置中可以改成直接选择文字后触发；
