### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by henrylee0324** [Yuanuo/cbeta-explorer#16]
您好
謝謝開發維護這個軟體
有些事希望您能幫忙
1. 希望提供24.02.18的Fedroa .rpm安裝包。

2. 在Linux環境下中文無法直接在程式中輸入，可以複製貼上。之前某一版本曾經修好過這個問題，但稍後此問題又復發。

3. 內建的字典辭典查詢系統是否可以增加查詢範圍。例如：我只想在某三部中查詢。

**Comment by Yuanuo** [comment]
你好，感谢使用和反馈。

1，最近一段时间我身边没有Linux或MacOS的系统环境用来编译程序。可能还要过一段时间。
2，等有Linux系统环境了我再检查一下。
3，目前较新的版本是有这个功能的，不知道你使用的版本有没有
![image](https://github.com/Yuanuo/cbeta-explorer/assets/10892032/13322733-b3d6-4e79-9fb5-36ac26e7afb5)

**Comment by henrylee0324** [comment]
谢谢您的回复
3. 目前我的版本没有此功能

**Comment by Yuanuo** [comment]
建议使用新版，
![image](https://github.com/Yuanuo/cbeta-explorer/assets/10892032/96956854-1433-433a-9771-344109d29dd2)

**Comment by Yuanuo** [comment]
1，已发布rpm安装包（24.05.17版）；
2，经测试未发现无法输入中文的问题；
3，查词条/词义均可定义查词范围；
