### ISSUE TITLE
T0220号经检索有问题

### ISSUE THREAD

**Issue by k79e** [Yuanuo/cbeta-explorer#17]
打开0220b 0220c 都是0220a一样的

还有t0220的书签/收藏有问题. 有时候就第一个能用. 
或者就加了一个收藏然后下次启动根本没法用.

**Comment by Yuanuo** [comment]
你好，感谢反馈

1，t0220是《大般若经》，我认为这应该是一部经，所以没有细分。因此a,b,c...打开都是t0220。
2，试了下可能是a,b,c导致的问题。下次会修复。

**Comment by k79e** [comment]
@Yuanuo 在打开小品中品经的时候 那个分类里面写的后面字母不一样, 因为现在abc打开都一样, 所以根本就打不开别的品.

我测试了添加别的经文到书签里面, 然后关闭当前标签. 重启之后也是只有第一个能用.

**Comment by Yuanuo** [comment]
感谢反馈。已修复
