### ISSUE TITLE
建议添加goto行首和引用复制功能, 和文段行首显示功能.

### ISSUE THREAD

**Issue by k79e** [Yuanuo/cbeta-explorer#18]
就是和原版阅读器一样的那3个功能.

原书换行太频繁, 除非是要看扫图版去定位才会用. 
每一段前面显示一次行号这样比较实用.  就和原版一样.

引用复制和goto行首是最重要的功能,  因为他能定位到精确位置, 
而且这个信息是可复制可传播的. 不像书签是给自己用的.

**Comment by Yuanuo** [comment]
你好，感谢使用和反馈。

本程序支持复制引用和根据（部分）引用信息定位还原。

比如，
复制引用的信息：
《修行本起經》卷1：「佛不妄笑，願說其意。」(CBETA 2023.Q4, T03, no. 184, p. 462b13-14)

定位还原的方式：
方法1：在快捷检索（Ctrl+G）中输入 #T03, no. 184, p. 462b13-14 ；
方法2：在打开的《修行本起经》阅读视图中，跳转本书目录（Ctrl+T）中输入 #p. 462b13-14 ；


目前CBETA维护的经藏数据中大多数都有行信息，所以基本能精确定位到行，定位到段落应该是不如定位到行更方便的。

**Comment by k79e** [comment]
我说的段落只是显示出来每个段落前面的行号.

对于ctrl+t 目前没发现输入 "《T0220o 大般若波羅蜜多經》卷95：「罗汉求。」(CBETA 2023.Q1, T05, no. 220, p. 526b26)"
这样信息能跳转.

**Comment by k79e** [comment]
目前不支持原样格式复制进去就跳转, 很不方便. 而且在用户输入行号的时候, 已经不会去选择目录了.
所以应当回车直接跳转.

应当支持直接输入复制出的信息就能跳过去.
应当在+g +t两个模式都支持这样功能比较好?

当前也没发现输入"#p. 257c25" 在对应经能跳过去.
这个对应一个经 输入行号跳转是**非常不可行的**
行号不是一个明确坐标, 因为他依赖正藏的册数. 一个经跨了册是没法定位的. 他既有高行号也有低行号!!!
