### ISSUE TITLE
有A开头的注释没显示

### ISSUE THREAD

**Issue by k79e** [Yuanuo/cbeta-explorer#19]
《大般若波羅蜜多經》卷93：「如來於離一切智真[A1]如非相應非不相應」(CBETA 2023.Q1, T05, no. 220, p. 518a26-27)
[A1] 如【CB】【麗-CB】【磧-CB】，加【大】(cf. K01n0001_p0797b17; Q01_p0505b14)。　

阅读器打开没有注释标记呢.

**Comment by Yuanuo** [comment]
感谢反馈。已修复
