### ISSUE TITLE
应当支持以引用复制原格式直接跳转

### ISSUE THREAD

**Issue by k79e** [Yuanuo/cbeta-explorer#21]
引用复制的格式是官方程序的, 而且官方程序支持直接以那个跳转.
现在程序还得用#开头 很不方便.
而且如我前面说的, 用户输入完整的"坐标" 意图就是想要去用跳转, 而不是导航, 所以这个时候 直接回车就跳转过去是最好的.

**Comment by Yuanuo** [comment]
现在已经是用引用复制的东西直接粘贴就行，不用#号，但要自己选择并回车确认
________________________________
发件人: k79e ***@***.***>
发送时间: Thursday, March 28, 2024 8:29:36 AM
收件人: Yuanuo/cbeta-explorer ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Yuanuo/cbeta-explorer] 应当支持以引用复制原格式直接跳转 (Issue #21)


引用复制的格式是官方程序的, 而且官方程序支持直接以那个跳转.
现在程序还得用#开头 很不方便.
而且如我前面说的, 用户输入完整的"坐标" 意图就是想要去用跳转, 而不是导航, 所以这个时候 直接回车就跳转过去是最好的.

―
