### ISSUE TITLE
建议支持显示段首行号

### ISSUE THREAD

**Issue by k79e** [Yuanuo/cbeta-explorer#22]
![image](https://github.com/Yuanuo/cbeta-explorer/assets/6483602/19d8eed2-4179-4dec-8301-6eaec019317c)
就像这样的.

**Comment by Yuanuo** [comment]
不清楚具体用途。

如果是网页版，这个段首连接很有必要。因为该标记可以复制并分享到其他网页，再点击时会返回该网页并定位到该段落处。
但在本地版程序中并不存在这种操作方式，所以无实际意义。
显示的这几个字符也不具有唯一性，只是在段首显示这几个字符，复制到别处也不具有可以定位还原的操作性。

**Comment by Yuanuo** [comment]
如果需要，可以在本地版程序中加入：
![image](https://github.com/Yuanuo/cbeta-explorer/assets/10892032/370d4d0a-b5d7-4454-aa48-5c44d45d56e0)

可以在快捷检索中输入 #pT03p0462b1307 定位还原到该处。

**Comment by k79e** [comment]
官方的网页版段首还就是没法复制的.
段首就不是程序跳转而是粗略定位用的. 否则一大堆引用谁知道是什么位置的!?? 
尤其是在一些严谨的场合, 更需要定位. 但是逐行不需要, 逐行是扫图用的. 程序跳转是后期才有的功能.
而且据我所知, 大正藏自己的系统**到现在也不支持电子化定位**
那你说行号是干啥的? 恐怕大多数人才是理解错误了. 误以为行号是电子化定位用的.
电子化定位是后期发展出来的功能. 而且程序跳转和行号是两码事, 不显示行号也可以跳转.

部分行号虽然没有唯一性但是结合卷信息还是有用处. 否则官方的人也不会闲着没事开发这个功能.

比如研究的时候需要粗略定位, 用户直接打出来行号速度可能都比引用复制来的快.
而且写东西的时候, 放那种引用复制一大堆也不好看. 
引用复制一个就要占用一行, 而粗略定位一行可以有很多个信息.
写文献的人很多直接就扔个书名, 尚且没有页数或者卷数. 所以这个粗略的定位. 是很有用的.

大量引用的时候, 复制逐行不方便, 格式不美观. 而且现在问题也不是美观不美观, 而是根本没法用.
逐行决定不可以被复制到可以传阅的文本里面, 决定不可以. 否则失去了电子化的最大意义. 就是程序检索.
语句都被打断了 怎么搜索呢!? 肯定是搜不成!! 就别提写给别人看的文献了, 自己的东西自己都搜不了.

所以 行号, 程序跳转 ,段首. 3个东西用处各不相同.
其行号作用是纸质书定位, 后期被发展, 碰巧作为程序定位. 但是并不能改变其本质, 因为他打断了语句. 
为了保留语句连贯性, 才有了段号的产生.

如果说要发展出更有特色的功能, 我建议直接快捷键复制定位信息算了, 而且输出信息可以用变量自由组合. 用户自定义设计格式.

**Comment by Yuanuo** [comment]
还是没有明白这个段首行号有什么实际用途。

作为引用复制的话，现在的方式应该是合适的，

> 《修行本起經》卷1：「佛知一切皆有疑意，便告摩訶[A1]目揵連：『汝能為怛薩阿竭說本起乎？』」(CBETA 2023.Q4, T03, no. 184, p. 461b1)
[A1]目揵連【大】＊，目連【明】＊

里面已经包含了人能看懂的 经名、卷数、文字。以及括号里的对于程序可用的定位信息。

其实不管是行号还是段号，这些字符对人是没有意义的，这些信息只是用来可以精确地定位到某处。
如果你觉得，现在的复制引用信息里面的精确定位到某句话这个不合适，反而只需要精确定位到段首处。这一点实在让人难以理解。如果你是想用这个定位信息进行交流的话，精确定位到某句话明显比只定位到段首处更有价值。

再补充一下，pT03p0462b1307 这一串字符还不能进行定位，这里面还没有卷信息。如果加上卷信息会变成 pT03xxxxp0462b1307 。仅仅引用这一串字符来分享传播应该是不合适的。

**Comment by Yuanuo** [comment]
另外，程序中目前有的 折行显示 和 折页显示 两个功能，当时只是觉得做起来简单就加上了，实际也不清楚具体用途。

如果你一定要显示一个段首行号，现在的折页显示功能已经是这个效果了，

![image](https://github.com/Yuanuo/cbeta-explorer/assets/10892032/bbf800df-9e13-4225-b9e5-3e2a3e97439c)

**Comment by k79e** [comment]
折页目前我看起来和逐行差不多.

因为你总是以你自己的角度来看待事情当然觉得没必要.
你总是想着精准定位, 又咋能明白粗略定位的用途呢!??

**Comment by k79e** [comment]
这东西具体到底一共多少种用法, 我也不清楚. 
但是他应该主要是给人看的, 不是用来快速跳转的. (看也分很多个背景, 经文这东西不是小说一样一看就完了不是么?)
指不定有人见了段号他buff加成还能变高呢. 这东西谁说的准.

比如你这个程序现在跳转他往下多跳了2行, 不准. 假如有段号, 就更容易发现.  (假设跳转的位置 前面正好有一行被分段了)

诸法自性谁能穷尽, 唯诸如来能尽了知.
我等凡夫于一字之义尚不能穷, 况诸法性.
事物繁多,在下告辞!! 保重!!
