### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by Pantyhose-X** [Yuanuo/cbeta-explorer#9]
1、Linux 只发布，[.AppImage](https://github.com/AppImage/AppImageKit)版，任何的Linux系统，都可以安装运行。
2、增加TTS朗读功能。
3、增加查看[.djvu](https://djvu.sourceforge.net)格式.
4、經文資料檔zip 不知道如何导入 有待优化
5、软件里的删除功能键，不应该删除本地磁盘里的文件
6、创建一个群组在 https://rvlt.gg 一起交流

**Comment by Yuanuo** [comment]
感谢使用。

1、有空了可以研究一下打包成AppImage的可行性；
2、TTS功能主要涉及到语音库准确性问题，多音字和生僻字基本难以保证；最终效果难以控制；
3、本程序主要用于查看和搜索CBETA经藏数据。暂时没有发现适用于查看djvu格式的用途和意义。

**Comment by Yuanuo** [comment]
4、經文資料檔zip 在设置选项中”数据源“处替换即可。
5、目前为止本程序为数据只读的程序，无相应删除功能。
